Repository 349Team/portal-aulas-online-backend, pull requests merged in 2023-06, with the labels that each got.

#87 Concluir curso e baixar certificado
  portal-aulas-api/courses/migrations/0018_completedcourserelation_and_more.py
  portal-aulas-api/courses/migrations/0019_progresscourserelation_and_more.py
  portal-aulas-api/courses/migrations/0020_merge_20230623_2350.py
  portal-aulas-api/courses/models.py
  portal-aulas-api/courses/serializers/course.py
  portal-aulas-api/lessons/tools.py
  portal-aulas-api/lessons/views.py
  portal-aulas-api/requirements.txt
  portal-aulas-api/user/serializers.py
Labels: Backend, Aluno

#92 Adicionar seção nas aulas e ordena-las usando drag and drop
  portal-aulas-api/courses/migrations/0021_coursecategory.py
  portal-aulas-api/courses/migrations/0022_course_categories_order.py
  portal-aulas-api/courses/migrations/0023_alter_coursecategory_lessons_order.py
  portal-aulas-api/courses/migrations/0024_merge_20230626_1858.py
  portal-aulas-api/courses/models.py
  portal-aulas-api/courses/serializers/category.py
  portal-aulas-api/courses/serializers/course.py
  portal-aulas-api/courses/urls.py
  portal-aulas-api/courses/views.py
  portal-aulas-api/lessons/migrations/0010_coursecategory.py
  portal-aulas-api/lessons/migrations/0011_delete_coursecategory.py
  portal-aulas-api/lessons/migrations/0012_lesson_category.py
  portal-aulas-api/lessons/migrations/0013_merge_20230626_1856.py
  portal-aulas-api/lessons/models.py
  portal-aulas-api/lessons/serializers.py
  portal-aulas-api/lessons/views.py
Labels: Aprimoramento, Backend, Professor

#93 Anotações de aulas
  portal-aulas-api/user/migrations/0016_anotation.py
  portal-aulas-api/user/migrations/0017_alter_anotation_user.py
  portal-aulas-api/user/migrations/0018_remove_anotation_anotations_anotation_link_and_more.py
  portal-aulas-api/user/migrations/0019_remove_anotation_title.py
  portal-aulas-api/user/migrations/0020_anotation_course_anotation_lesson.py
  portal-aulas-api/user/migrations/0021_remove_anotation_link.py
  portal-aulas-api/user/models.py
  portal-aulas-api/user/serializers.py
  portal-aulas-api/user/urls.py
  portal-aulas-api/user/views.py
Labels: Aprimoramento, Backend

#98 Ajustes finais sprint 3
  portal-aulas-api/lessons/views.py
  portal-aulas-api/media/appendices/courses/lessons/static.txt
  portal-aulas-api/media/certificate-logo.png
  portal-aulas-api/media/images/courses/lessons/static.txt
  portal-aulas-api/media/videos/courses/lessons/static.txt
Labels: Backend, Final Release
