Repository 349Team/portal-aulas-online-backend, pull requests merged in 2023-05, with the labels that each got.

#50 44 enviar token de cadastro do professor por e mail
  portal-aulas-api/api/settings.py
  portal-aulas-api/user/services.py
  portal-aulas-api/user/urls.py
  portal-aulas-api/user/views.py
Labels: Backend

#62 56 b fazer streming arquivos de video
  portal-aulas-api/lessons/views.py
Labels: Backend, Aluno

#69 68 b arrumar as mensagens de erro
  Makefile
  portal-aulas-api/user/migrations/0011_alter_user_cpf.py
  portal-aulas-api/user/models.py
  portal-aulas-api/user/serializers.py
  portal-aulas-api/user/views.py
Labels: Backend, Correções
